---
- name: ensure_pip sanity check
  fail: msg="Required variables->PIP_TARGET_VERSION missed"
  when: PIP_TARGET_VERSION is not defined

- name: Check specfic verion of pip exist or not
  command: "{{ pip_executable }} -V"
  register: result_pip_is_installed
  ignore_errors: True

- block:
  - name: Create tempoary build dir to install pip
    command: python -c 'import tempfile; print tempfile.mkdtemp()'
    register: result_pip_build_dir
  - name: Download get-pip.py
    get_url: url={{ pip_source_url }} dest={{ result_pip_build_dir.stdout }}
  - name: Build pip
    shell: "{{ python_executable }} get-pip.py"
    args:
      chdir: "{{ result_pip_build_dir.stdout }}"
  always:
    - name: msg="Remove temp dir->{{ result_pip_build_dir.stdout }}"
      file: dest="{{ result_pip_build_dir.stdout }}/"  state=absent
  become: true
  when: result_pip_is_installed | failed

- name: Ensure pip is at the latest version
  pip: name=pip state=latest