- include_vars: "{{ ansible_os_family | lower }}.yaml"

- name: make sure unzip utility is installed
  package: name=unzip
  become: yes

- name: download and extract grav source
  unarchive:
    src: "https://getgrav.org/download/core/grav/{{ grav_version }}"
    dest: "{{ ansible_env.HOME }}"
    remote_src: yes

- name: install required php plugins
  yum : name={{ item }} state=latest
  with_items: '{{ package_php_extras }}'

- name: try init grav
  script: initgrav.sh "{{ BASE_DIR }}" "{{ ansible_env.HOME }}" "{{ SITE_ROOT }}"

- name: set grav permission
  script: setperm.sh "{{ SITE_ROOT }}" "{{ ansible_user_id }}"
  become: yes

- name: install grav backup cron job
  cron: name="backup grav" minute="30" hour="6" job="cd {{ BASE_DIR }}/bin/gv_backup && sh backup.sh"
  when: ansible_virtualization_type not in [ 'lxc', 'docker' ]








