# Create Django env in Nginx+uWSGI
- hosts: all
  vars:
    - project_name: test
    - target_version: 2.7
  any_errors_fatal: true
  gather_facts: true
  #roles:
    #- { role: service_nginx, nginx_feature: uwsgi }
    #- uwsgi
  #  - ensure_python
  #  - ensure_pip
  #  - ensure_virtualenv
  tasks:
    - name: Install django in virtualenv
      shell: source ~/.bashrc && mkvirtualenv wxgigo && pip install django=="1.8.*" && deactivate
