- name: sanity check
  fail: msg="Required variables->SITE_NAME"
  when: SITE_NAME is not defined

- name: configure phpfpm for grav
  include_role: name=configure_phpfpm
  vars:
    CONTAINER: nginx

- include_role: name=configure_nginx
  vars:
    NGINX_FEATURE: phpfpm

- name: main
  include: "tasks/{{ ansible_os_family | lower }}/default.yaml"
  become: yes
