---
dependencies:
  - {role: ensure_php, PHP_VERSION: PHP_TARGET_VERSION}
  - role: ensure_epel_release
    when: ansible_os_family | lower == "redhat"
  - role: ensure_ius_release
    when: ansible_os_family | lower == "redhat"
