---
kube_groupname_master: master
kube_repo_template: kube-aliyun.j2
kube_repo_file: /etc/yum.repos.d/kubernetes.repo
kube_repo_base_url: https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-{{ ansible_architecture }}/
kube_repo_gpg_key: |
  https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg
  https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg
kube_packages:
  - ethtool
  - ebtables
  - docker
  - kubelet
  - kubectl
  - kubeadm
