---
- name: Check required variables
  fail: msg="Required variables->project_name missed"
  when: project_name is not defined

- name: Install django in virtualenv
  shell: source ~/.bashrc && mkvirtualenv {{ project_name }} && pip install django=="1.8.*" && deactivate

# setup project specfic nginx configuration
  - name: Copy Nginx configuration
    template: src=nginx/project-nginx.conf dest=/etc/nginx/conf.d/{{ project_name}}-nginx.conf
    notify: restart nginx
