---
- name: Check required variables
  fail: msg="Required variables->project_name missed"
  when: project_name is not defined

- include_vars: "{{ ansible_os_family | lower }}.yml"

- block:
  - name: Generate nginx configuration file
    template: src={{ nginx_conf_template }} dest={{ nginx_conf_file }}
  - name: Enable nginx service
    service: name=nginx enabled=yes
  become: true