---
# For main master node
- block:
  - name: init main master node
    command: kubeadm init --pod-network-cidr=10.244.0.0/16
    register: result_master_init
  - name: try generate worker node join command file
    command: ls {{ kube_script_join_node }} || grep "kubeadm join --token" result_master_init.stdout > {{ kube_script_join_node }} 
  - name: try generate master member node join command file
    command: ls {{ kube_script_join_master_member }} || grep "kubeadm join --master --token" result_master_init.stdout > {{ kube_script_join_master_member }} 
    ignore_errors: True 
  - name: setup master environment
    shell:  mkdir -p $HOME/.kube && sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && sudo chown $(id -u):$(id -g) $HOME/.kube/config
  - name: apply network policy
    command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  when: "{{ kube_node_role }}" == "master"

# For master member nodes
- name: join master member node
  command: sh {{ kube_script_join_master_member }} 
  when: "{{ kube_node_role }}" == "master_member"

# For normal nodes
- name: join node
  command: sh {{ kube_script_join_node }} 
  when: "{{ kube_node_role }}" == "node"
  #when: "'{{ kube_group_node }}' in group_names"

