---
# For main master node
- name: Init master node
  include: "master.yaml"
  when: kube_node_role == "master"

# For master member nodes
- name: join master member node
  command: hostvars[groups["master"][0]]["kube_command_mm_join"]
  when: kube_node_role == "master_member"

# For normal nodes
- name: join node
  command: hostvars[groups["master"][0]]["kube_command_node_join"]
  when: kube_node_role == "node"
  #when: "'{{ kube_group_node }}' in group_names"

