---
# For main master node
- block:
  include "master.yaml"
  when: kube_node_role == "master"

# For master member nodes
- name: join master member node
  command: hostvars[groups["master"][0]]["kube_command_join_master_member"]
  when: kube_node_role == "master_member"

# For normal nodes
- name: join node
  command: hostvars[groups["master"][0]]["kube_command_join_node"]
  when: kube_node_role == "node"
  #when: "'{{ kube_group_node }}' in group_names"

