---
- name: "Check if kubernetes are installed or not"
  command: "kubectl version"
  ignore_errors: true
  changed_when: false
  register: result_kube_installed

- name: execute OS specific operations
  include: "default.yaml"
  when: result_kube_installed|failed
