---
- name: "Check if kubeadm installed or not"
  command: "kubeadm version"
  ignore_errors: true
  changed_when: false
  register: result_kubeadm_installed

- name: Configure kubernetes
  include: "default.yaml"
  when: result_kubeadm_installed|succeeded
