# For main master node
- name: init main master node
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  register: result_master_init

# reset environment
- block:
  - name: Clean home config dir
    shell: rm -fr $HOME/.kube
  - name: Setup master environment
    shell:  mkdir -p $HOME/.kube && sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && sudo chown $(id -u):$(id -g) $HOME/.kube/config
  - name: restart kubelet service to reload new cert if nessary
    service: name=kubelet state=restarted

- name: apply network policy
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: Set kube_command_node_join variable for future reference
  set_fact: kube_command_node_join={{ result_master_init.stdout|regex_search('kubeadm join --token .*') }}

- name: Set kube_command_mm_join variable for future reference
  set_fact: kube_command_mm_join={{ result_master_init.stdout|regex_search('kubeadm join --master --token .*') }}
  #currently don't support master HA
  ignore_errors: true
