---
# reset environment
- name: Reset kube stuff
  command: kubeadm reset

- name: Clean home config dir
  shell: rm -fr $HOME/.kube

- name: restart kubelet service to reload new cert if nessary
  service: name=kubelet state=restarted

