- name: Check required variables
  fail: msg="Required variables->project_name, project_home missed"
  when: project_name is not defined or project_home is not defined
  tags: configure_uwsgi

# construct a uwsgi platform dir for invoking different tasks and variables under specific dir
- name: Register platform related variable
  set_fact:
    uwsgi_platform_dirname: "{{ ansible_os_family | lower }}{{ ansible_distribution_major_version }}"
  tags: configure_uwsgi

- name: Load Linux distribution specfic tasks
  include: "{{ uwsgi_platform_dirname }}/default.yaml"
  tags: configure_uwsgi


