- name: Check required variables
  fail: msg="Required variables->normal_user, normal_user_pass"
  when: normal_user is not defined or normal_user_pass is not defined

- name: Check user already exist or not
  shell: id {{ normal_user }}
  register: result_user_existed
  ignore_errors: true

- name: "Add user: {{ normal_user }}"
  user: name={{ normal_user }} password={{ normal_user_pass | password_hash('sha512') }}
  when: result_user_existed | failed