- name: install shadowsocks server
  shell: pip install shadowsocks

- name: make shadowsocks root dir exist
  file: path="{{ SS_ROOT }}" state=directory owner="{{ ansible_user_id }}" group="{{ ansible_group_id }}"

- name: install shadowsocks server config
  template: src=shadowsocks.json.j2 dest="{{ SS_ROOT }}/shadowsocks.json"

- block:
  - name: install systemd service script
    template: src=shadowsocks.service.j2 dest=/etc/systemd/system/shadowsocks.service mode=0644
  - name: systemd reload daemon
    shell: systemctl daemon-reload
  when: ansible_distribution_major_version|int == 7

- name: install sysv5 service script
  template: src=shadowsocks.sysv.j2 dest=/etc/init.d/shadowsocks mode=0644
  when: ansible_distribution_major_version|int < 7

- name: enable and start service
  service: name=shadowsocks enabled=yes state=restarted
  when: ansible_virtualization_type not in [ 'lxc', 'docker' ]




