- name: Check required variables
  fail: msg="Required variables->target_version missed"
  when: target_version is not defined

- name: Check if specific version of PHP is installed or not
  command: php-fpm -v
  register: result_phpfpm_installed
  ignore_errors: true

- block:
  - include_vars: "{{ target_version }}.yml"
  - include_role: name=ensure_epel
  - include_role: name=ensure_ius_release
  - name: Install specific php-fpm
    package: name={{ phpfpm_package_name }}
    become: yes
  when: result_phpfpm_installed | failed
