- include_vars: "centos7.yaml"

- name: Install yum-utils
  yum: name=yum-utils
- name: Make sure there no pending yum transaction
  command: yum-complete-transaction --cleanup-only
- name: Install kubernetes repository
  template: src={{ kube_repo_template }} dest={{ kube_repo_file }}
- name: Yum install packages
  yum : name={{ item }} state=latest
  with_items: '{{ kube_packages }}'

# Issue: https://stackoverflow.com/questions/46726216/kubelet-fails-to-get-cgroup-stats-for-docker-and-kubelet-services
- name: Patch kubelet systemd start script for above issue
  lineinfile:
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '^Environment="KUBELET_CGROUP_ARGS='
    line: Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=systemd --runtime-cgroups=/systemd/system.slice --kubelet-cgroups=/systemd/system.slice"