---
- name: "Check if kubernetes are installed or not"
  command: "kubectl version"
  ignore_errors: true
  changed_when: false
  register: result_kube_installed

- name: execute OS specific operations
  include_tasks: "{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yaml"
  when: result_kube_installed|failed
