---
- name: Check required variables
  fail: msg="Required variables->target_version missed"
  when: target_version is not defined

- name: "Check if specific version of python is installed or not"
  command: "{{ python_executable }} --version"
  ignore_errors: true
  changed_when: false
  register: result_python_is_installed

- name: Excecute distribution related tasks
  include: tasks/{{ ansible_os_family | lower }}/default.yml
  when: result_python_is_installed | failed