---
- name: Check required variables
  fail: msg="Required variables->target_version missed"
  when: target_version is not defined

- name: Check if virtualenv has been installed or not
  shell: virtualenv --version
  register: result_virtualenv_is_installed
  ignore_errors: true

- name: Install virtualenv
  include: default.yaml
  when: result_virtualenv_is_installed | failed






