---
- name: Check if epel-release can be installed or not
  fail: msg="epel-release packages can not be installed on {{ ansible_distribution }}"
  when: ansible_os_family|lower != "redhat"

- name: Check if epel-release installed or not
  command: yum list installed epel-release
  register: result_epel_installed
  ignore_errors: true

- name: Install epel-release package
  package: name="https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
  when: result_epel_installed | failed
  become: yes


