---
- hosts: all
  any_errors_fatal: true
  gather_facts: true
  roles:
  - ensure_kubernetes

- hosts: master
  any_errors_fatal: true
  gather_facts: true
  roles:
  - {role: configure_kubernetes, kube_node_role: "master"}

- hosts: master_member
  any_errors_fatal: true
  gather_facts: true
  roles:
  - {role: configure_kubernetes, kube_node_role: "master_member"}

- hosts: node
  any_errors_fatal: true
  gather_facts: true
  roles:
  - {role: configure_kubernetes, kube_node_role: "node"}
