- hosts: all
  any_errors_fatal: true
  gather_facts: true
  roles:
    - ensure_nginx
    - ensure_phpfpm
    - {role: configure_phpfpm, SITE_NAME: 192.168.1.2, CONTAINER: nginx }
    - {role: configure_nginx, SITE_NAME: 192.168.1.2, SITE_ROOT: /www, NGINX_FEATURE: phpfpm }
