---
- include_vars: "{{ nginx_feature }}.yml"
  when: nginx_feature is defined

- block:
  - name: Install Nginx package
    yum: name=nginx state=present

  - name: Copy Nginx configuration
    template: src=project-nginx.conf dest=/etc/nginx/conf.d/{{ project_name}}-nginx.conf
    notify: restart nginx

  - name: Insert firewalld rule for Nginx
    firewalld: port={{ nginx_listen }}/tcp permanent=true state=enabled immediate=yes
    ignore_errors: yes

  - name: Enable Nginx service and make sure it started
    service: name=nginx state=started enabled=yes
  become: true